FROM golang:{%.GoVersion%}-alpine AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o /bin/api ./cmd/api && mkdir -p migrations

FROM alpine:3

WORKDIR /app

RUN adduser -D -H app && chown app /app

COPY --from=build /bin/api /app/api
COPY --from=build /app/migrations ./migrations

USER app

EXPOSE {%.Port%}

ENTRYPOINT ["/app/api"]
