package cli

import (
	"os"
	"strings"
	"unicode"

	"github.com/ViitoJooj/devx/internal/cli/config"
	"github.com/ViitoJooj/devx/internal/cli/utils"
	"github.com/ViitoJooj/devx/pkg/errorx"
	"github.com/spf13/cobra"
)

var crudLsJSON bool

var crudLsCmd = &cobra.Command{
	Use:     "ls",
	Aliases: []string{"list"},
	Short:   "List the cruds in internal/containers",
	Args:    cobra.NoArgs,
	Run:     crudLs,
}

func init() {
	crudLsCmd.Flags().BoolVar(&crudLsJSON, "json", false, "output as json")
}

type crudItem struct {
	Name    string   `json:"name"`
	Route   string   `json:"route"`
	DB      string   `json:"db"`
	Access  []string `json:"access"`
	OpenAPI bool     `json:"openapi"`
}

func crudLs(cmd *cobra.Command, args []string) {

	project := loadAPIProject()

	items := make([]crudItem, 0)
	var rows [][]string

	access, _ := tableAccess(project)

	for _, folder := range cruds(project) {
		names := namesFromFolder(project, folder)

		item := crudItem{
			Name:    folder,
			Route:   "/v1/" + names.KebabPlural,
			DB:      crudDatabase(project, folder),
			OpenAPI: documented(project, names.KebabPlural),
		}
		var accessText string
		item.Access, accessText = crudAccess(project, access, folder, names)
		items = append(items, item)

		documented := "no"
		if item.OpenAPI {
			documented = "yes"
		}

		rows = append(rows, []string{item.Name, item.Route, item.DB, accessText, documented})
	}

	printList(crudLsJSON, items, []string{"NAME", "ROUTE", "DB", "ACCESS", "OPENAPI"}, rows)
}

// cruds returns the containers generated by crud add (server is part of the project base).
func cruds(project *config.Project) []string {

	entries, _ := os.ReadDir(project.Path("internal", "containers"))

	var output []string
	for _, entry := range entries {
		if entry.IsDir() && entry.Name() != "server" {
			output = append(output, entry.Name())
		}
	}

	return output
}

func resolveCrud(project *config.Project, input string) utils.Names {

	names, err := utils.NewEntityNames(input)
	if err != nil {
		errorx.InvalidName(input)
	}

	for _, folder := range cruds(project) {
		if folder == names.FolderPlural {
			return names
		}
		if folder == strings.ReplaceAll(strings.ToLower(input), "-", "") {
			return namesFromFolder(project, folder)
		}
	}

	if input := strings.ToLower(input); (input == "server" || input == "servers") && project.Exists("internal", "containers", "server") {
		errorx.ContainerIsBase("server")
	}

	errorx.ContainerNotFound(names.FolderPlural)
	return names
}

func namesFromFolder(project *config.Project, folder string) utils.Names {

	names, err := utils.NewNames(snake(entityName(project, utils.Names{FolderPlural: folder})))
	if err != nil {
		errorx.InvalidName(folder)
	}

	names.FolderPlural = folder
	return names
}

func snake(pascal string) string {
	var output strings.Builder
	for i, r := range pascal {
		if unicode.IsUpper(r) && i > 0 {
			output.WriteByte('_')
		}
		output.WriteRune(unicode.ToLower(r))
	}
	return output.String()
}
